require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/AbcSize:
  Max: 21

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 12

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 4
