name: Lint
on: pull_request
jobs:
  lint:
    runs-on: macOS-13
    permissions:
      pull-requests: write
      statuses: write
    env:
      DEVELOPER_DIR: '/Applications/Xcode_14.3.1.app/Contents/Developer'
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - run: bundle exec rake periphery:install
      - run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
