name: Lint
on: [pull_request]
jobs:
  lint:
    runs-on: macOS-12
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: bundle install
      - run: bundle exec rake periphery:install
      - run: bundle exec danger
