name: Test
on: [push]
jobs:
  unit-test:
    runs-on: macOS-12
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.6.9
          - 2.7.5
          - 3.0.4
          - 3.1.2
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec rake
