name: Test
on: [push]
jobs:
  unit-test:
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - run: bin/download_periphery
      - run: bundle install
      - run: bundle exec rake
