name: Test
on: [push]
jobs:
  unit-test:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - run: bundle install
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec rake
